/**
 * Hikari biz code naming convention.
 *
 * Use UPPER_SNAKE_CASE strings: `<domain>_<semantic>` or `<domain>_<subdomain>_<semantic>`.
 *
 * Examples:
 * - COMMON_VALIDATION_FAILED
 * - AUTH_TOKEN_INVALID
 * - USER_EMAIL_ALREADY_USED
 * - GALGAME_NOT_FOUND
 *
 * Rules:
 * - The object key and string value must be identical.
 * - `domain` is a stable business/API domain, not a database table name.
 * - `semantic` describes the stable client-visible reason, not the current implementation detail.
 * - Do not add success codes here; success is represented by `success: true`.
 * - Do not rename or reuse an exposed code. Add a new code and migrate callers instead.
 */
export const HIKARI_BIZ_CODE = {
  COMMON_BAD_REQUEST: 'COMMON_BAD_REQUEST',
  COMMON_VALIDATION_FAILED: 'COMMON_VALIDATION_FAILED',
  COMMON_UNEXPECTED_ERROR: 'COMMON_UNEXPECTED_ERROR',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_RATE_LIMITED: 'COMMON_RATE_LIMITED',
  COMMON_SERVICE_UNAVAILABLE: 'COMMON_SERVICE_UNAVAILABLE',
  COMMON_NOT_IMPLEMENTED: 'COMMON_NOT_IMPLEMENTED',

  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_ADMIN_ONLY: 'AUTH_ADMIN_ONLY',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_FAMILY_BLOCKED: 'AUTH_FAMILY_BLOCKED',
  AUTH_VERIFICATION_CODE_EXPIRED: 'AUTH_VERIFICATION_CODE_EXPIRED',
  AUTH_VERIFICATION_CODE_INVALID: 'AUTH_VERIFICATION_CODE_INVALID',
  AUTH_VERIFICATION_CODE_TOO_FREQUENT: 'AUTH_VERIFICATION_CODE_TOO_FREQUENT',
  AUTH_VERIFICATION_TOKEN_EXPIRED: 'AUTH_VERIFICATION_TOKEN_EXPIRED',
  AUTH_VERIFICATION_TOKEN_INVALID: 'AUTH_VERIFICATION_TOKEN_INVALID',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_USED: 'USER_EMAIL_ALREADY_USED',
  USER_EMAIL_DOMAIN_NOT_ALLOWED: 'USER_EMAIL_DOMAIN_NOT_ALLOWED',
  USER_NAME_ALREADY_USED: 'USER_NAME_ALREADY_USED',
  USER_NAME_CHANGED_ONCE: 'USER_NAME_CHANGED_ONCE',
  USER_INVALID_PASSWORD: 'USER_INVALID_PASSWORD',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  USER_BANNED: 'USER_BANNED',
  USER_REGISTER_CLOSED: 'USER_REGISTER_CLOSED',

  REVIEW_GROUP_APPLICATION_NOT_FOUND: 'REVIEW_GROUP_APPLICATION_NOT_FOUND',
  REVIEW_GROUP_APPLICATION_PENDING_EXISTS: 'REVIEW_GROUP_APPLICATION_PENDING_EXISTS',
  REVIEW_GROUP_APPLICATION_ALREADY_MEMBER: 'REVIEW_GROUP_APPLICATION_ALREADY_MEMBER',
  REVIEW_GROUP_APPLICATION_NOT_PENDING: 'REVIEW_GROUP_APPLICATION_NOT_PENDING',

  CHECK_IN_ALREADY_DONE: 'CHECK_IN_ALREADY_DONE',
  CHECK_IN_MAKE_UP_LIMIT_REACHED: 'CHECK_IN_MAKE_UP_LIMIT_REACHED',
  CHECK_IN_INSUFFICIENT_POINTS: 'CHECK_IN_INSUFFICIENT_POINTS',

  TELEGRAM_NOT_LINKED: 'TELEGRAM_NOT_LINKED',
  TELEGRAM_ALREADY_LINKED: 'TELEGRAM_ALREADY_LINKED',
  TELEGRAM_CODE_INVALID: 'TELEGRAM_CODE_INVALID',
  TELEGRAM_CODE_EXPIRED: 'TELEGRAM_CODE_EXPIRED',
  TELEGRAM_CODE_TOO_FREQUENT: 'TELEGRAM_CODE_TOO_FREQUENT',

  FAVORITE_COLLECTION_NOT_FOUND: 'FAVORITE_COLLECTION_NOT_FOUND',
  FAVORITE_COLLECTION_ALREADY_EXISTS: 'FAVORITE_COLLECTION_ALREADY_EXISTS',
  FAVORITE_COLLECTION_NOT_OWNER: 'FAVORITE_COLLECTION_NOT_OWNER',
  FAVORITE_COLLECTION_NOT_ALLOW_VIEW: 'FAVORITE_COLLECTION_NOT_ALLOW_VIEW',
  FAVORITE_COLLECTION_DEFAULT_NOT_ALLOW_DELETE: 'FAVORITE_COLLECTION_DEFAULT_NOT_ALLOW_DELETE',
  FAVORITE_ITEM_NOT_FOUND: 'FAVORITE_ITEM_NOT_FOUND',

  DECORATION_NOT_FOUND: 'DECORATION_NOT_FOUND',
  DECORATION_UNAVAILABLE: 'DECORATION_UNAVAILABLE',
  DECORATION_NOT_PURCHASABLE: 'DECORATION_NOT_PURCHASABLE',
  DECORATION_ALREADY_OWNED: 'DECORATION_ALREADY_OWNED',
  DECORATION_NOT_OWNED: 'DECORATION_NOT_OWNED',
  DECORATION_INSUFFICIENT_POINTS: 'DECORATION_INSUFFICIENT_POINTS',

  CONDITION_PRESET_NOT_FOUND: 'CONDITION_PRESET_NOT_FOUND',
  CONDITION_PRESET_IN_USE: 'CONDITION_PRESET_IN_USE',

  GALGAME_NOT_FOUND: 'GALGAME_NOT_FOUND',
  GALGAME_DOWNLOAD_NOT_FOUND: 'GALGAME_DOWNLOAD_NOT_FOUND',
  GALGAME_DOWNLOAD_SOURCE_UNAVAILABLE: 'GALGAME_DOWNLOAD_SOURCE_UNAVAILABLE',
  LIGHT_NOVEL_NOT_FOUND: 'LIGHT_NOVEL_NOT_FOUND',
  MANGA_NOT_FOUND: 'MANGA_NOT_FOUND',
  MANGA_CHAPTER_NOT_FOUND: 'MANGA_CHAPTER_NOT_FOUND',
  VOLUME_NOT_FOUND: 'VOLUME_NOT_FOUND',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  PERSON_NOT_FOUND: 'PERSON_NOT_FOUND',
  PRODUCER_NOT_FOUND: 'PRODUCER_NOT_FOUND',
  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
  /** The requested id was merged into another entry; `details.merged_into` carries the survivor. */
  WIKI_RESOURCE_MERGED: 'WIKI_RESOURCE_MERGED',
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POLL_NOT_FOUND: 'POLL_NOT_FOUND',
  POLL_CLOSED: 'POLL_CLOSED',
  POLL_OPTION_INVALID: 'POLL_OPTION_INVALID',
  POLL_MULTIPLE_NOT_ALLOWED: 'POLL_MULTIPLE_NOT_ALLOWED',
  POLL_LOCKED: 'POLL_LOCKED',
  POLL_VOTE_LOCKED: 'POLL_VOTE_LOCKED',
  POLL_MAX_CHOICES: 'POLL_MAX_CHOICES',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_THREAD_NOT_FOUND: 'COMMENT_THREAD_NOT_FOUND',
  COMMENT_EDIT_WINDOW_CLOSED: 'COMMENT_EDIT_WINDOW_CLOSED',
  COMMENT_ATTACHMENT_LIMIT_EXCEEDED: 'COMMENT_ATTACHMENT_LIMIT_EXCEEDED',
  COMMENT_PARENT_INVALID: 'COMMENT_PARENT_INVALID',
  REPORT_ALREADY_PENDING: 'REPORT_ALREADY_PENDING',
  SECTION_NOT_FOUND: 'SECTION_NOT_FOUND',
  TOPIC_NOT_FOUND: 'TOPIC_NOT_FOUND',

  EMOJI_SET_NOT_FOUND: 'EMOJI_SET_NOT_FOUND',
  EMOJI_SET_NAME_TAKEN: 'EMOJI_SET_NAME_TAKEN',
  EMOJI_SET_LIMIT_EXCEEDED: 'EMOJI_SET_LIMIT_EXCEEDED',
  EMOJI_SET_NOT_SUBSCRIBABLE: 'EMOJI_SET_NOT_SUBSCRIBABLE',
  EMOJI_LIMIT_EXCEEDED: 'EMOJI_LIMIT_EXCEEDED',
  EMOJI_NAME_TAKEN: 'EMOJI_NAME_TAKEN',

  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_IN_USE: 'MEDIA_IN_USE',
  MEDIA_SCAN_ALREADY_RUNNING: 'MEDIA_SCAN_ALREADY_RUNNING',

  READER_EPUB_NOT_AVAILABLE: 'READER_EPUB_NOT_AVAILABLE',
  READER_BOOKMARK_NOT_FOUND: 'READER_BOOKMARK_NOT_FOUND',
  READER_ANNOTATION_NOT_FOUND: 'READER_ANNOTATION_NOT_FOUND',

  MODERATION_UNAVAILABLE: 'MODERATION_UNAVAILABLE',
  MODERATION_MALFORMED: 'MODERATION_MALFORMED',

  EPUB_REVIEW_INVALID_FILE: 'EPUB_REVIEW_INVALID_FILE',
  EPUB_REVIEW_NOT_FOUND: 'EPUB_REVIEW_NOT_FOUND',
  EPUB_REPORT_FILE_SUPERSEDED: 'EPUB_REPORT_FILE_SUPERSEDED',
  EPUB_REPORT_VERSION_UNAVAILABLE: 'EPUB_REPORT_VERSION_UNAVAILABLE',

  CHANGE_REQUEST_NOT_FOUND: 'CHANGE_REQUEST_NOT_FOUND',
  CHANGE_REQUEST_RESOURCE_NOT_FOUND: 'CHANGE_REQUEST_RESOURCE_NOT_FOUND',
  CHANGE_REQUEST_RESOURCE_UNSUPPORTED: 'CHANGE_REQUEST_RESOURCE_UNSUPPORTED',
  CHANGE_REQUEST_RESOURCE_LOCKED: 'CHANGE_REQUEST_RESOURCE_LOCKED',
  CHANGE_REQUEST_ALREADY_OPEN: 'CHANGE_REQUEST_ALREADY_OPEN',
  CHANGE_REQUEST_INVALID_CHANGESET: 'CHANGE_REQUEST_INVALID_CHANGESET',
  CHANGE_REQUEST_NOT_OPEN: 'CHANGE_REQUEST_NOT_OPEN',

  REVISION_NOT_FOUND: 'REVISION_NOT_FOUND',
  REVISION_NOT_ROLLBACKABLE: 'REVISION_NOT_ROLLBACKABLE',
  REVISION_ROLLBACK_NOOP: 'REVISION_ROLLBACK_NOOP',

  PERMISSION_GROUP_NOT_FOUND: 'PERMISSION_GROUP_NOT_FOUND',
  PERMISSION_GROUP_NAME_TAKEN: 'PERMISSION_GROUP_NAME_TAKEN',
  PERMISSION_GROUP_SYSTEM_READONLY: 'PERMISSION_GROUP_SYSTEM_READONLY',
  PERMISSION_KEY_INVALID: 'PERMISSION_KEY_INVALID',
  PERMISSION_ESCALATION_DENIED: 'PERMISSION_ESCALATION_DENIED',
  PERMISSION_GROUP_MEMBER_EXISTS: 'PERMISSION_GROUP_MEMBER_EXISTS',
  PERMISSION_GROUP_MEMBER_NOT_FOUND: 'PERMISSION_GROUP_MEMBER_NOT_FOUND',

  DEVELOPER_APP_LIMIT_EXCEEDED: 'DEVELOPER_APP_LIMIT_EXCEEDED',
} as const

export type HikariBizCode = (typeof HIKARI_BIZ_CODE)[keyof typeof HIKARI_BIZ_CODE]

export interface ApiFieldError {
  field: string
  message: string
  code?: string
}

export interface ApiError {
  code: HikariBizCode
  message: string
  field_errors?: ApiFieldError[]
  details?: Record<string, unknown>
  retryable?: boolean
}
