// Coordinates use the full image canvas, including transparent margins.
export const SCENE_MOMENTS = [
  {
    id: 'walk',
    src: '/images/contribute/shion/01.webp',
    position: 0.22,
    width: 6.4,
    ratio: '2 / 3',
    anchor: 97.4,
    depth: 1.8,
    shadow: { x: 35, y: 97.4, width: 60, height: 7, contact_width: 24, contact_height: 3 },
  },
  {
    id: 'chase',
    src: '/images/contribute/shion/02.webp',
    position: 0.8,
    width: 6.4,
    ratio: '2 / 3',
    anchor: 97.2,
    depth: 1.8,
    shadow: { x: 42, y: 97.2, width: 55, height: 7, contact_width: 24, contact_height: 3 },
  },
  {
    id: 'read',
    src: '/images/contribute/shion/03.webp',
    position: 0.6,
    width: 5.2,
    ratio: '1',
    anchor: 96.5,
    depth: 1.8,
    shadow: { x: 50, y: 94, width: 82, height: 11, contact_width: 0, contact_height: 0 },
  },
  {
    id: 'sort',
    src: '/images/contribute/shion/04.webp',
    position: 0.36,
    width: 5.8,
    ratio: '1',
    anchor: 94.6,
    depth: 1.8,
    shadow: { x: 52, y: 93, width: 91, height: 9, contact_width: 0, contact_height: 0 },
  },
  {
    id: 'page',
    src: '/images/contribute/shion/05.webp',
    position: 0.7,
    width: 7.8,
    ratio: '1',
    anchor: 99,
    depth: 1.8,
    shadow: { x: 60, y: 98.3, width: 36, height: 7, contact_width: 23, contact_height: 3 },
  },
  {
    id: 'search',
    src: '/images/contribute/shion/06.webp',
    position: 0.48,
    width: 6.4,
    ratio: '2 / 3',
    anchor: 98.2,
    depth: 1.3,
    shadow: { x: 52, y: 98, width: 33, height: 7, contact_width: 23, contact_height: 3 },
  },
  {
    id: 'stroll',
    src: '/images/contribute/shion/07.webp',
    position: 0.3,
    width: 6.4,
    ratio: '2 / 3',
    anchor: 97.1,
    depth: 1.8,
    shadow: { x: 74, y: 97.1, width: 50, height: 7, contact_width: 24, contact_height: 3 },
  },
  {
    id: 'listen',
    src: '/images/contribute/shion/08.webp',
    position: 0.66,
    width: 6.4,
    ratio: '2 / 3',
    anchor: 98,
    depth: 1.8,
    shadow: { x: 53, y: 98, width: 32, height: 7, contact_width: 23, contact_height: 3 },
  },
] as const
